### ISSUE TITLE
Support for including X509Certificate in signed XML

### ISSUE THREAD

**Issue by donalddylla** [benoist/xmldsig#18]
I need to include my certificate chain in my signed XML and I find no API to help with this.  I can use code like the following to insert the certificate but not the trust chain.

key_info = ''
in_key = false
certificate.to_pem.each_line  do |line|
    in_key=false  if line.match('-----END CERTIFICATE-----')
    key_info += line   if in_key
    in_key=true  if line.match('-----BEGIN CERTIFICATE-----')
 end
 unsigned_xml = unsigned_xml.gsub(/<X509Certificate>/, "<X509Certificate>\n#{key_info.strip}")

**Comment by benoist** [comment]
This library only supports signing, building the signature elements is not (yet) implemented.

Do you have an example of an signed XML message with the complete chain in it?

**Comment by donalddylla** [comment]
Here is one example that I have seen
https://www.aleksey.com/xmlsec/tests/aleksey-xmldsig-01/enveloping-rsa-x509chain.xml
Others can also be found at the bottom of https://www.aleksey.com/xmlsec/xmldsig-verifier.html

Thanks for the reply.  Your gem looks helpful.

Donald

**Comment by benoist** [comment]
Ok well in that case I think it should be possible to create a signature object with chain included and use your certificate to sign the method as described in the README.
You could probably use the OpenSSL::X509::Store to load your certificates, I'm sure but I think the store has a method "chain" that contains all the certificates in the store. Otherwise you'd have to create a list of certificates yourself by splitting them up.
If you need help with that just let me know.

**Comment by donalddylla** [comment]
Thanks,  I could not get OpenSSL::X509::Store to return back a chain with any values but I will manage to put something together that will work well enough.

Donald
